INSERT INTO sakila.film VALUES (190,
                                'CREEPERS KANE',
                                'A Awe-Inspiring Reflection of a Squirrel And a Boat who must Outrace a Car in A Jet Boat',
                                2006,
                                '1',
                                4.99,
                                172,
                                '23.99',
                                'NC-17',
                                'Trailers,Behind the Scenes',
                                '2006-02-15 05:03:42');
